" Pathogen package manager. Install all future packages to .vim/bundle.
call pathogen#infect()
set runtimepath+=$GOROOT/misc/vim

" Color schemes and syntaxing.
" Try to use Solarized theme if we can :)
filetype plugin indent on
syntax enable
colorscheme desert
if isdirectory($HOME . '/.vim/bundle/solarized.vim')
    set t_Co=256
    set background=dark
    colorscheme solarized
endif

set tabstop=4 shiftwidth=4 expandtab smarttab
set nocompatible
set autoindent
set showcmd
set number 
set ignorecase
set smartcase
set incsearch
" Highlight search, but remove highlight after pressing enter
set hlsearch
nnoremap <CR> :noh<CR><CR>

" Always display the status line. Status line is:
" filename[+ if modified][RO if readonly] [line, column]
set laststatus=2
set statusline=%F%m%r\ [%l,%v]

" Map escape to ii in insert and visual modes
inoremap ii <Esc>
vnoremap ii <Esc> 
" Tab to switch focus in splits
map <Tab> <C-W>w
" <Enter> for word-completion.
set completeopt=longest,menuone
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Padding between cursor and number of lines on screen
set scrolloff=5

" Ignore .git, virtualenv, etc for CTRL-P file searching.
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|env)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ }
